Auth/issue 2 implement auth functionalities
TasmiaZerin1128/Pen-and-Paper pull request #4
Opened 2023-03-14 05:24 UTC by TasmiaZerin1128

Completed authentication using JWT

2023-03-15 14:40 UTC, edge555 commented on controllers/auth.controller.js
> +            algorithm: "HS256",
keep the algorithm name in env folder

2023-03-15 14:40 UTC, edge555 commented on controllers/auth.controller.js
> +                algorithm: "HS256",
keep the algorithm name in env folder

2023-03-15 14:50 UTC, edge555 commented on utils/jwtToken.js
> +}
Deleting the cookie should be enough. refer to this link for better understanding, https://stackoverflow.com/questions/37959945/how-to-destroy-jwt-tokens-on-logout

2023-03-15 14:55 UTC, edge555 commented on utils/errorHandler.js
> +
also add isOperational property

2023-03-15 15:54 UTC, TasmiaZerin1128 commented on utils/jwtToken.js
> +}
Fixed this in the 'issue - 2 : logout done' commit

2023-03-16 13:01 UTC, rafaelragib requested changes

2023-03-16 13:01 UTC, rafaelragib commented on controllers/auth.controller.js
> +    const data = await authService.register(req.body);
what will happen if the body is empty?

2023-03-16 13:01 UTC, rafaelragib commented on services/user.service.js
> +    throw new ValidationError(err.message, 500, true);
why we are using ValidationError here? shouldn't it be a common error?

2023-03-16 13:01 UTC, rafaelragib commented on services/user.service.js
try to remove if else staircase condition from the project as much as possible

2023-03-16 13:01 UTC, rafaelragib commented on services/auth.service.js
> +    const userExists = await userService.getUserbyUsername(user.username, false);
```suggestion
    const userExists = await userService.getUserByUsername(user.username, false);
```

2023-03-16 13:01 UTC, rafaelragib commented on controllers/auth.controller.js
> +const jwt = require("jsonwebtoken");
if this is not used in this file I think it is better we remove it

2023-03-16 13:01 UTC, rafaelragib commented on services/auth.service.js
> +  const userValid = userUtils.userValidator(
try to pass the whole user object and then destruct it inside the function. This will increase code readability

2023-03-16 13:01 UTC, rafaelragib commented on controllers/user.controller.js
> +    const data = await userService.getUserbyUsername(req.params.username, true);
from where the username is coming from? the route doesn't have any param value. This function will fail.

2023-03-17 05:55 UTC, TasmiaZerin1128 commented on controllers/auth.controller.js
> +    const data = await authService.register(req.body);
The validator function in the authService will return false as the fields are empty.

2023-03-17 05:56 UTC, TasmiaZerin1128 commented on controllers/auth.controller.js
> +const jwt = require("jsonwebtoken");
Sorry, removed this in the issue 3 branch. Removing it.

2023-03-17 06:04 UTC, TasmiaZerin1128 commented on controllers/user.controller.js
> +    const data = await userService.getUserbyUsername(req.params.username, true);
This route has a username param value, line no 7 in user.route file.

2023-03-17 06:05 UTC, TasmiaZerin1128 commented on services/user.service.js
> +    throw new ValidationError(err.message, 500, true);
Yes, changing it.

2023-03-17 10:47 UTC, rafaelragib commented on controllers/auth.controller.js
> +    const data = await authService.register(req.body);
I have looked into the userValidator method and I couldn't find any check for an empty body. We will look into this in the next meeting.

2023-03-17 10:49 UTC, rafaelragib commented on controllers/user.controller.js
> +    const data = await userService.getUserbyUsername(req.params.username, true);
yeah it looks good. resolving the conversation.

2023-03-20 19:18 UTC, merged